a, b, c = input().split()
a = int(a)
b = int(b)
c = int(c)
if a > b > c:
    print("%i" %c)
    print("%i" %b)
    print("%i""\n" %a)
    print("%i" %a)
    print("%i" %b)
    print("%i" %c)
if a > c > b:
    print("%i" %b)
    print("%i" %c)
    print("%i""\n" %a)
    print("%i" %a)
    print("%i" %b)
    print("%i" %c)
if c > b > a:
    print("%i" %a)
    print("%i" %b)
    print("%i""\n" %c)
    print("%i" %a)
    print("%i" %b)
    print("%i" %c)
if c > a > b:
    print("%i" %b)
    print("%i" %a)
    print("%i""\n" %c)
    print("%i" %a)
    print("%i" %b)
    print("%i" %c)
if b > a > c:
    print("%i" %c)
    print("%i" %a)
    print("%i""\n" %b)
    print("%i" %a)
    print("%i" %b)
    print("%i" %c)
if b > c > a:
    print("%i" %a)
    print("%i" %c)
    print("%i""\n" %b)
    print("%i" %a)
    print("%i" %b)
    print("%i" %c)

